print("Waseem")
print("2+3")
print("I am learning from codanics")
print("Right now i am in Math make smart")
print("This is my second day of lesson")
print("I have craze to learn python and R programming")
print("I hope i will learn this in 40 days")
print("I am excited to learn this course")
print("I am the sngle one to learn this course")
print("I want to be a data scientist")